const keycodeEn = [
  {
    lowerCase: '`',
    upperCase: '~',
    code: 'Backquote',
  },
  {
    lowerCase: '1',
    upperCase: '!',
    code: 'Digit1',
  },
  {
    lowerCase: '2',
    upperCase: '@',
    code: 'Digit2',
  },
  {
    lowerCase: '3',
    upperCase: '#',
    code: 'Digit3',
  },
  {
    lowerCase: '4',
    upperCase: '$',
    code: 'Digit4',
  },
  {
    lowerCase: '5',
    upperCase: '%',
    code: 'Digit5',
  },
  {
    lowerCase: '6',
    upperCase: '^',
    code: 'Digit6',
  },
  {
    lowerCase: '7',
    upperCase: '&',
    code: 'Digit7',
  },
  {
    lowerCase: '8',
    upperCase: '*',
    code: 'Digit8',
  },
  {
    lowerCase: '9',
    upperCase: '(',
    code: 'Digit9',
  },
  {
    lowerCase: '0',
    upperCase: ')',
    code: 'Digit0',
  },
  {
    lowerCase: '-',
    upperCase: '_',
    code: 'Minus',
  },
  {
    lowerCase: '=',
    upperCase: '+',
    code: 'Equal',
  },
  {
    lowerCase: 'Backspace',
    upperCase: null,
    code: 'Backspace',
  },
  {
    lowerCase: 'Tab',
    upperCase: null,
    code: 'Tab',
  },
  {
    lowerCase: 'q',
    upperCase: 'Q',
    code: 'KeyQ',
  },
  {
    lowerCase: 'w',
    upperCase: 'W',
    code: 'KeyW',
  },
  {
    lowerCase: 'e',
    upperCase: 'E',
    code: 'KeyE',
  },
  {
    lowerCase: 'r',
    upperCase: 'R',
    code: 'KeyR',
  },
  {
    lowerCase: 't',
    upperCase: 'T',
    code: 'KeyT',
  },
  {
    lowerCase: 'y',
    upperCase: 'Y',
    code: 'KeyY',
  },
  {
    lowerCase: 'u',
    upperCase: 'U',
    code: 'KeyU',
  },
  {
    lowerCase: 'i',
    upperCase: 'I',
    code: 'KeyI',
  },
  {
    lowerCase: 'o',
    upperCase: 'O',
    code: 'KeyO',
  },
  {
    lowerCase: 'p',
    upperCase: 'P',
    code: 'KeyP',
  },
  {
    lowerCase: '[',
    upperCase: '{',
    code: 'BracketLeft',
  },
  {
    lowerCase: ']',
    upperCase: '}',
    code: 'BracketRight',
  },
  {
    lowerCase: '\\',
    upperCase: '|',
    code: 'Backslash',
  },
  {
    lowerCase: 'a',
    upperCase: 'A',
    code: 'KeyA',
  },
  {
    lowerCase: 's',
    upperCase: 'S',
    code: 'KeyS',
  },
  {
    lowerCase: 'd',
    upperCase: 'D',
    code: 'KeyD',
  },
  {
    lowerCase: 'f',
    upperCase: 'F',
    code: 'KeyF',
  },
  {
    lowerCase: 'g',
    upperCase: 'G',
    code: 'KeyG',
  },
  {
    lowerCase: 'h',
    upperCase: 'H',
    code: 'KeyH',
  },
  {
    lowerCase: 'j',
    upperCase: 'J',
    code: 'KeyJ',
  },
  {
    lowerCase: 'k',
    upperCase: 'K',
    code: 'KeyK',
  },
  {
    lowerCase: 'l',
    upperCase: 'L',
    code: 'KeyL',
  },
  {
    lowerCase: ';',
    upperCase: ':',
    code: 'Semicolon',
  },
  {
    lowerCase: "'",
    upperCase: '"',
    code: 'Quote',
  },
  {
    lowerCase: 'Enter',
    upperCase: null,
    code: 'Enter',
  },
  {
    lowerCase: 'Shift',
    upperCase: null,
    code: 'ShiftLeft',
  },
  {
    lowerCase: 'z',
    upperCase: 'Z',
    code: 'KeyZ',
  },
  {
    lowerCase: 'x',
    upperCase: 'X',
    code: 'KeyX',
  },
  {
    lowerCase: 'c',
    upperCase: 'C',
    code: 'KeyC',
  },
  {
    lowerCase: 'v',
    upperCase: 'V',
    code: 'KeyV',
  },
  {
    lowerCase: 'b',
    upperCase: 'B',
    code: 'KeyB',
  },
  {
    lowerCase: 'n',
    upperCase: 'N',
    code: 'KeyN',
  },
  {
    lowerCase: 'm',
    upperCase: 'M',
    code: 'KeyM',
  },
  {
    lowerCase: ',',
    upperCase: '<',
    code: 'Comma',
  },
  {
    lowerCase: '.',
    upperCase: '>',
    code: 'Period',
  },
  {
    lowerCase: '/',
    upperCase: '?',
    code: 'Slash',
  },
  {
    lowerCase: 'Shift',
    upperCase: null,
    code: 'ShiftRight',
  },
  {
    lowerCase: 'Ctrl',
    upperCase: null,
    code: 'ControlLeft',
  },
  {
    lowerCase: 'Fn',
    upperCase: null,
    code: '',
  },
  {
    lowerCase: 'Win',
    upperCase: null,
    code: 'Win',
  },
  {
    lowerCase: 'Alt',
    upperCase: null,
    code: 'AltLeft',
  },
  {
    lowerCase: ' ',
    upperCase: null,
    code: 'Space',
  },
  {
    lowerCase: 'Alt',
    upperCase: null,
    code: 'AltRight',
  },
  {
    lowerCase: 'Ctrl',
    upperCase: null,
    code: 'ControlRight',
  },
];

export const rowKeyEn = [
  [
    {
      lowerCase: '`',
      upperCase: '~',
      code: 'Backquote',
      class: 'key',
    },
    {
      lowerCase: '1',
      upperCase: '!',
      code: 'Digit1',
      class: 'key',
    },
    {
      lowerCase: '2',
      upperCase: '@',
      code: 'Digit2',
      class: 'key',
    },
    {
      lowerCase: '3',
      upperCase: '#',
      code: 'Digit3',
      class: 'key',
    },
    {
      lowerCase: '4',
      upperCase: '$',
      code: 'Digit4',
      class: 'key',
    },
    {
      lowerCase: '5',
      upperCase: '%',
      code: 'Digit5',
      class: 'key',
    },
    {
      lowerCase: '6',
      upperCase: '^',
      code: 'Digit6',
      class: 'key',
    },
    {
      lowerCase: '7',
      upperCase: '&',
      code: 'Digit7',
      class: 'key',
    },
    {
      lowerCase: '8',
      upperCase: '*',
      code: 'Digit8',
      class: 'key',
    },
    {
      lowerCase: '9',
      upperCase: '(',
      code: 'Digit9',
      class: 'key',
    },
    {
      lowerCase: '0',
      upperCase: ')',
      code: 'Digit0',
      class: 'key',
    },
    {
      lowerCase: '-',
      upperCase: '_',
      code: 'Minus',
      class: 'key',
    },
    {
      lowerCase: '=',
      upperCase: '+',
      code: 'Equal',
      class: 'key',
    },
    {
      lowerCase: 'Backspace',
      upperCase: null,
      code: 'Backspace',
      class: 'key key-backspace',
    },
  ],
  [
    {
      lowerCase: 'Tab',
      upperCase: null,
      code: 'Tab',
      class: 'key key-tab',
    },
    {
      lowerCase: 'q',
      upperCase: 'Q',
      code: 'KeyQ',
      class: 'key',
    },
    {
      lowerCase: 'w',
      upperCase: 'W',
      code: 'KeyW',
      class: 'key',
    },
    {
      lowerCase: 'e',
      upperCase: 'E',
      code: 'KeyE',
      class: 'key',
    },
    {
      lowerCase: 'r',
      upperCase: 'R',
      code: 'KeyR',
      class: 'key',
    },
    {
      lowerCase: 't',
      upperCase: 'T',
      code: 'KeyT',
      class: 'key',
    },
    {
      lowerCase: 'y',
      upperCase: 'Y',
      code: 'KeyY',
      class: 'key',
    },
    {
      lowerCase: 'u',
      upperCase: 'U',
      code: 'KeyU',
      class: 'key',
    },
    {
      lowerCase: 'i',
      upperCase: 'I',
      code: 'KeyI',
      class: 'key',
    },
    {
      lowerCase: 'o',
      upperCase: 'O',
      code: 'KeyO',
      class: 'key',
    },
    {
      lowerCase: 'p',
      upperCase: 'P',
      code: 'KeyP',
      class: 'key',
    },
    {
      lowerCase: '[',
      upperCase: '{',
      code: 'BracketLeft',
      class: 'key',
    },
    {
      lowerCase: ']',
      upperCase: '}',
      code: 'BracketRight',
      class: 'key',
    },
    {
      lowerCase: '\\',
      upperCase: '|',
      code: 'Backslash',
      class: 'key key-slash',
    },
  ],
  [
    {
      lowerCase: 'CapsLock',
      upperCase: null,
      code: 'CapsLock',
      class: 'key-caps',
    },
    {
      lowerCase: 'a',
      upperCase: 'A',
      code: 'KeyA',
      class: 'key',
    },
    {
      lowerCase: 's',
      upperCase: 'S',
      code: 'KeyS',
      class: 'key',
    },
    {
      lowerCase: 'd',
      upperCase: 'D',
      code: 'KeyD',
      class: 'key',
    },
    {
      lowerCase: 'f',
      upperCase: 'F',
      code: 'KeyF',
      class: 'key',
    },
    {
      lowerCase: 'g',
      upperCase: 'G',
      code: 'KeyG',
      class: 'key',
    },
    {
      lowerCase: 'h',
      upperCase: 'H',
      code: 'KeyH',
      class: 'key',
    },
    {
      lowerCase: 'j',
      upperCase: 'J',
      code: 'KeyJ',
      class: 'key',
    },
    {
      lowerCase: 'k',
      upperCase: 'K',
      code: 'KeyK',
      class: 'key',
    },
    {
      lowerCase: 'l',
      upperCase: 'L',
      code: 'KeyL',
      class: 'key',
    },
    {
      lowerCase: ';',
      upperCase: ':',
      code: 'Semicolon',
      class: 'key',
    },
    {
      lowerCase: "'",
      upperCase: '"',
      code: 'Quote',
      class: 'key',
    },
    {
      lowerCase: 'Enter',
      upperCase: null,
      code: 'Enter',
      class: 'key key-enter',
    },
  ],
  [
    {
      lowerCase: 'Shift',
      upperCase: null,
      code: 'ShiftLeft',
      class: 'key shift shift-left',
    },
    {
      lowerCase: 'z',
      upperCase: 'Z',
      code: 'KeyZ',
      class: 'key',
    },
    {
      lowerCase: 'x',
      upperCase: 'X',
      code: 'KeyX',
      class: 'key',
    },
    {
      lowerCase: 'c',
      upperCase: 'C',
      code: 'KeyC',
      class: 'key',
    },
    {
      lowerCase: 'v',
      upperCase: 'V',
      code: 'KeyV',
      class: 'key',
    },
    {
      lowerCase: 'b',
      upperCase: 'B',
      code: 'KeyB',
      class: 'key',
    },
    {
      lowerCase: 'n',
      upperCase: 'N',
      code: 'KeyN',
      class: 'key',
    },
    {
      lowerCase: 'm',
      upperCase: 'M',
      code: 'KeyM',
      class: 'key',
    },
    {
      lowerCase: ',',
      upperCase: '<',
      code: 'Comma',
      class: 'key',
    },
    {
      lowerCase: '.',
      upperCase: '>',
      code: 'Period',
      class: 'key',
    },
    {
      lowerCase: '/',
      upperCase: '?',
      code: 'Slash',
      class: 'key',
    },
    {
      lowerCase: 'Shift',
      upperCase: null,
      code: 'ShiftRight',
      class: 'key shift shift-right',
    },
  ],
  [
    {
      lowerCase: 'Ctrl',
      upperCase: null,
      code: 'ControlLeft',
      class: 'key key-ctrl ctrl-left',
    },
    {
      lowerCase: 'Fn',
      upperCase: null,
      code: 'Fn',
      class: 'key key-fn',
    },
    {
      lowerCase: 'Win',
      upperCase: null,
      code: 'Win',
      class: 'key key-win',
    },
    {
      lowerCase: 'Alt',
      upperCase: null,
      code: 'AltLeft',
      class: 'key key-alt alt-left',
    },
    {
      lowerCase: ' ',
      upperCase: null,
      code: 'Space',
      class: 'key key-space',
    },
    {
      lowerCase: 'Alt',
      upperCase: null,
      code: 'AltRight',
      class: 'key key-alt alt-right',
    },
    {
      lowerCase: 'Ctrl',
      upperCase: null,
      code: 'ControlRight',
      class: 'key key-ctrl ctrl-right',
    },
  ],
];

export default keycodeEn;
