export const rowKeyRu = [
  [
    {
      lowerCase: 'ё',
      upperCase: 'Ё',
      code: 'Backquote',
      class: 'key',
    },
    {
      lowerCase: '1',
      upperCase: '!',
      code: 'Digit1',
      class: 'key',
    },
    {
      lowerCase: '2',
      upperCase: '"',
      code: 'Digit2',
      class: 'key',
    },
    {
      lowerCase: '3',
      upperCase: '№',
      code: 'Digit3',
      class: 'key',
    },
    {
      lowerCase: '4',
      upperCase: ';',
      code: 'Digit4',
      class: 'key',
    },
    {
      lowerCase: '5',
      upperCase: '%',
      code: 'Digit5',
      class: 'key',
    },
    {
      lowerCase: '6',
      upperCase: ':',
      code: 'Digit6',
      class: 'key',
    },
    {
      lowerCase: '7',
      upperCase: '?',
      code: 'Digit7',
      class: 'key',
    },
    {
      lowerCase: '8',
      upperCase: '*',
      code: 'Digit8',
      class: 'key',
    },
    {
      lowerCase: '9',
      upperCase: '(',
      code: 'Digit9',
      class: 'key',
    },
    {
      lowerCase: '0',
      upperCase: ')',
      code: 'Digit0',
      class: 'key',
    },
    {
      lowerCase: '-',
      upperCase: '_',
      code: 'Minus',
      class: 'key',
    },
    {
      lowerCase: '=',
      upperCase: '+',
      code: 'Equal',
      class: 'key',
    },
    {
      lowerCase: 'Backspace',
      upperCase: null,
      code: 'Backspace',
      class: 'key key-backspace',
    },
  ],
  [
    {
      lowerCase: 'Tab',
      upperCase: null,
      code: 'Tab',
      class: 'key key-tab',
    },
    {
      lowerCase: 'й',
      upperCase: 'Й',
      code: 'KeyQ',
      class: 'key',
    },
    {
      lowerCase: 'ц',
      upperCase: 'Ц',
      code: 'KeyW',
      class: 'key',
    },
    {
      lowerCase: 'у',
      upperCase: 'У',
      code: 'KeyE',
      class: 'key',
    },
    {
      lowerCase: 'к',
      upperCase: 'К',
      code: 'KeyR',
      class: 'key',
    },
    {
      lowerCase: 'е',
      upperCase: 'Е',
      code: 'KeyT',
      class: 'key',
    },
    {
      lowerCase: 'н',
      upperCase: 'Н',
      code: 'KeyY',
      class: 'key',
    },
    {
      lowerCase: 'г',
      upperCase: 'Г',
      code: 'KeyU',
      class: 'key',
    },
    {
      lowerCase: 'ш',
      upperCase: 'Ш',
      code: 'KeyI',
      class: 'key',
    },
    {
      lowerCase: 'щ',
      upperCase: 'Щ',
      code: 'KeyO',
      class: 'key',
    },
    {
      lowerCase: 'з',
      upperCase: 'З',
      code: 'KeyP',
      class: 'key',
    },
    {
      lowerCase: 'х',
      upperCase: 'Х',
      code: 'BracketLeft',
      class: 'key',
    },
    {
      lowerCase: 'ъ',
      upperCase: 'Ъ',
      code: 'BracketRight',
      class: 'key',
    },
    {
      lowerCase: '\\',
      upperCase: '/',
      code: 'Backslash',
      class: 'key key-slash',
    },
  ],
  [
    {
      lowerCase: 'CapsLock',
      upperCase: null,
      code: 'CapsLock',
      class: 'key-caps',
    },
    {
      lowerCase: 'ф',
      upperCase: 'Ф',
      code: 'KeyA',
      class: 'key',
    },
    {
      lowerCase: 'ы',
      upperCase: 'Ы',
      code: 'KeyS',
      class: 'key',
    },
    {
      lowerCase: 'в',
      upperCase: 'В',
      code: 'KeyD',
      class: 'key',
    },
    {
      lowerCase: 'а',
      upperCase: 'А',
      code: 'KeyF',
      class: 'key',
    },
    {
      lowerCase: 'п',
      upperCase: 'П',
      code: 'KeyG',
      class: 'key',
    },
    {
      lowerCase: 'р',
      upperCase: 'Р',
      code: 'KeyH',
      class: 'key',
    },
    {
      lowerCase: 'о',
      upperCase: 'О',
      code: 'KeyJ',
      class: 'key',
    },
    {
      lowerCase: 'л',
      upperCase: 'Л',
      code: 'KeyK',
      class: 'key',
    },
    {
      lowerCase: 'д',
      upperCase: 'Д',
      code: 'KeyL',
      class: 'key',
    },
    {
      lowerCase: 'ж',
      upperCase: 'Ж',
      code: 'Semicolon',
      class: 'key',
    },
    {
      lowerCase: 'э',
      upperCase: 'Э',
      code: 'Quote',
      class: 'key',
    },
    {
      lowerCase: 'Enter',
      upperCase: null,
      code: 'Enter',
      class: 'key key-enter',
    },
  ],
  [
    {
      lowerCase: 'Shift',
      upperCase: null,
      code: 'ShiftLeft',
      class: 'key shift shift-left',
    },
    {
      lowerCase: 'я',
      upperCase: 'Я',
      code: 'KeyZ',
      class: 'key',
    },
    {
      lowerCase: 'ч',
      upperCase: 'Ч',
      code: 'KeyX',
      class: 'key',
    },
    {
      lowerCase: 'с',
      upperCase: 'С',
      code: 'KeyC',
      class: 'key',
    },
    {
      lowerCase: 'м',
      upperCase: 'М',
      code: 'KeyV',
      class: 'key',
    },
    {
      lowerCase: 'и',
      upperCase: 'И',
      code: 'KeyB',
      class: 'key',
    },
    {
      lowerCase: 'т',
      upperCase: 'Т',
      code: 'KeyN',
      class: 'key',
    },
    {
      lowerCase: 'ь',
      upperCase: 'Ь',
      code: 'KeyM',
      class: 'key',
    },
    {
      lowerCase: 'б',
      upperCase: 'Б',
      code: 'Comma',
      class: 'key',
    },
    {
      lowerCase: 'ю',
      upperCase: 'Ю',
      code: 'Period',
      class: 'key',
    },
    {
      lowerCase: '.',
      upperCase: ',',
      code: 'Slash',
      class: 'key',
    },
    {
      lowerCase: 'Shift',
      upperCase: null,
      code: 'ShiftRight',
      class: 'key shift shift-right',
    },
  ],
  [
    {
      lowerCase: 'Ctrl',
      upperCase: null,
      code: 'ControlLeft',
      class: 'key key-ctrl ctrl-left',
    },
    {
      lowerCase: 'Fn',
      upperCase: null,
      code: 'Fn',
      class: 'key key-fn',
    },
    {
      lowerCase: 'Win',
      upperCase: null,
      code: 'Win',
      class: 'key key-win',
    },
    {
      lowerCase: 'Alt',
      upperCase: null,
      code: 'AltLeft',
      class: 'key key-alt alt-left',
    },
    {
      lowerCase: ' ',
      upperCase: null,
      code: 'Space',
      class: 'key key-space',
    },
    {
      lowerCase: 'Alt',
      upperCase: null,
      code: 'AltRight',
      class: 'key key-alt alt-right',
    },
    {
      lowerCase: 'Ctrl',
      upperCase: null,
      code: 'ControlRight',
      class: 'key key-ctrl ctrl-right',
    },
  ],
];
